export interface CatalogCategory {
  id: string;
  code: string;
  name: string;
  translationKey: string;
  icon: string;
  displayOrder: number;
  definitions: CatalogDefinition[];
}

export interface CatalogDefinition {
  id: string;
  code: string;
  name: string;
  description: string;
  translationKey: string;
  descriptionTranslationKey: string;
  fieldType: 'boolean' | 'number' | 'time' | 'text' | 'scale' | 'select' | 'multi_select' | 'photo';
  dependencyCode?: string;
  allowsReminder?: boolean;
  allowsAttachment?: boolean;
  displayOrder: number;
  isCheckinButton?: boolean;
}

export const MONITORING_CATALOG: CatalogCategory[] = [
  {
    id: 'c1000000-0000-0000-0000-000000000001',
    code: 'daily_routine',
    name: 'Rotina diária',
    translationKey: 'monitoring.categories.daily_routine',
    icon: 'Utensils',
    displayOrder: 1,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000001',
        code: 'routine_meals',
        name: 'Alimentação (Refeições)',
        description: 'Acompanhamento de café da manhã, almoço, jantar e lanches.',
        translationKey: 'monitoring.defs.routine_meals',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_meals',
        fieldType: 'select',
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000002',
        code: 'routine_hydration',
        name: 'Hidratação',
        description: 'Controle de ingestão de copos de água e líquidos.',
        translationKey: 'monitoring.defs.routine_hydration',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_hydration',
        fieldType: 'number',
        allowsReminder: true,
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000003',
        code: 'routine_bath',
        name: 'Banho',
        description: 'Registro de realização do banho diário.',
        translationKey: 'monitoring.defs.routine_bath',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_bath',
        fieldType: 'boolean',
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000004',
        code: 'routine_personal_hygiene',
        name: 'Higiene pessoal e bucal',
        description: 'Escovação de dentes e cuidados higiênicos diários.',
        translationKey: 'monitoring.defs.routine_personal_hygiene',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_personal_hygiene',
        fieldType: 'boolean',
        displayOrder: 4,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000005',
        code: 'routine_clothing_change',
        name: 'Troca de roupa',
        description: 'Registro de troca e adequação das roupas do dia.',
        translationKey: 'monitoring.defs.routine_clothing_change',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_clothing_change',
        fieldType: 'boolean',
        displayOrder: 5,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000006',
        code: 'routine_restroom',
        name: 'Uso do banheiro',
        description: 'Frequência e normalidade de idas ao banheiro.',
        translationKey: 'monitoring.defs.routine_restroom',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_restroom',
        fieldType: 'select',
        displayOrder: 6,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000007',
        code: 'routine_diapers',
        name: 'Uso de fraldas',
        description: 'Controle de trocas e conforto no uso de fraldas.',
        translationKey: 'monitoring.defs.routine_diapers',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_diapers',
        fieldType: 'number',
        displayOrder: 7,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000008',
        code: 'routine_sleep',
        name: 'Sono e repouso',
        description: 'Horário de dormir, acordar e despertares noturnos.',
        translationKey: 'monitoring.defs.routine_sleep',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_sleep',
        fieldType: 'time',
        displayOrder: 8,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000009',
        code: 'routine_activities',
        name: 'Atividades e lazer',
        description: 'Caminhadas, leitura, televisão e exercícios orientados.',
        translationKey: 'monitoring.defs.routine_activities',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_activities',
        fieldType: 'text',
        displayOrder: 9,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000010',
        code: 'routine_housework',
        name: 'Rotina doméstica e quarto',
        description: 'Arrumação do quarto e troca de roupa de cama.',
        translationKey: 'monitoring.defs.routine_housework',
        descriptionTranslationKey: 'monitoring.defs.desc.routine_housework',
        fieldType: 'text',
        displayOrder: 10,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000002',
    code: 'medications',
    name: 'Medicamentos',
    translationKey: 'monitoring.categories.medications',
    icon: 'Pill',
    displayOrder: 2,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000011',
        code: 'meds_scheduled',
        name: 'Medicamentos programados',
        description: 'Horários, dosagens e lembretes prescritos.',
        translationKey: 'monitoring.defs.meds_scheduled',
        descriptionTranslationKey: 'monitoring.defs.desc.meds_scheduled',
        fieldType: 'boolean',
        allowsReminder: true,
        allowsAttachment: true,
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000012',
        code: 'meds_taken_confirmation',
        name: 'Confirmação de medicamento tomado',
        description: 'Registro de quem confirmou a ingestão e quando.',
        translationKey: 'monitoring.defs.meds_taken_confirmation',
        descriptionTranslationKey: 'monitoring.defs.desc.meds_taken_confirmation',
        fieldType: 'boolean',
        dependencyCode: 'meds_scheduled',
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000013',
        code: 'meds_not_taken_reason',
        name: 'Medicamento não tomado (com motivo)',
        description: 'Justificativa informada caso o remédio não seja ingerido.',
        translationKey: 'monitoring.defs.meds_not_taken_reason',
        descriptionTranslationKey: 'monitoring.defs.desc.meds_not_taken_reason',
        fieldType: 'text',
        dependencyCode: 'meds_scheduled',
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000014',
        code: 'meds_stock_management',
        name: 'Estoque de medicamentos',
        description: 'Controle de caixas e contagem de comprimidos restantes.',
        translationKey: 'monitoring.defs.meds_stock_management',
        descriptionTranslationKey: 'monitoring.defs.desc.meds_stock_management',
        fieldType: 'number',
        allowsReminder: true,
        displayOrder: 4,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000015',
        code: 'meds_low_stock_alert',
        name: 'Alerta de estoque baixo',
        description: 'Avisos antecipados para reposição de receitas.',
        translationKey: 'monitoring.defs.meds_low_stock_alert',
        descriptionTranslationKey: 'monitoring.defs.desc.meds_low_stock_alert',
        fieldType: 'boolean',
        dependencyCode: 'meds_stock_management',
        displayOrder: 5,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000003',
    code: 'observed_wellbeing',
    name: 'Bem-estar observado',
    translationKey: 'monitoring.categories.observed_wellbeing',
    icon: 'Heart',
    displayOrder: 3,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000016',
        code: 'wellbeing_mood',
        name: 'Humor observado',
        description: 'Estado de ânimo percebido (calmo, alegre, triste, irritado).',
        translationKey: 'monitoring.defs.wellbeing_mood',
        descriptionTranslationKey: 'monitoring.defs.desc.wellbeing_mood',
        fieldType: 'select',
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000017',
        code: 'wellbeing_energy',
        name: 'Disposição física relatada',
        description: 'Nível de energia observado no dia.',
        translationKey: 'monitoring.defs.wellbeing_energy',
        descriptionTranslationKey: 'monitoring.defs.desc.wellbeing_energy',
        fieldType: 'scale',
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000018',
        code: 'wellbeing_behavior_change',
        name: 'Mudança de comportamento observada',
        description: 'Anotações sobre agitação, isolamento ou agitação relatada.',
        translationKey: 'monitoring.defs.wellbeing_behavior_change',
        descriptionTranslationKey: 'monitoring.defs.desc.wellbeing_behavior_change',
        fieldType: 'text',
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000019',
        code: 'wellbeing_reported_pain',
        name: 'Dor relatada pela própria pessoa',
        description: 'Intensidade e localização declarada pelo próprio familiar.',
        translationKey: 'monitoring.defs.wellbeing_reported_pain',
        descriptionTranslationKey: 'monitoring.defs.desc.wellbeing_reported_pain',
        fieldType: 'scale',
        displayOrder: 4,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000020',
        code: 'wellbeing_weight',
        name: 'Peso corporal',
        description: 'Registros periódicos de pesagem.',
        translationKey: 'monitoring.defs.wellbeing_weight',
        descriptionTranslationKey: 'monitoring.defs.desc.wellbeing_weight',
        fieldType: 'number',
        displayOrder: 5,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000021',
        code: 'wellbeing_general_notes',
        name: 'Observações gerais do dia',
        description: 'Diário livre para apontamentos gerais da família.',
        translationKey: 'monitoring.defs.wellbeing_general_notes',
        descriptionTranslationKey: 'monitoring.defs.desc.wellbeing_general_notes',
        fieldType: 'text',
        displayOrder: 6,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000004',
    code: 'memory_routine',
    name: 'Memória e rotina cotidiana',
    translationKey: 'monitoring.categories.memory_routine',
    icon: 'Brain',
    displayOrder: 4,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000022',
        code: 'memory_unusual_forgetfulness',
        name: 'Esquecimentos incomuns observados',
        description: 'Dificuldade pontual em localizar objetos ou lembrar rotinas.',
        translationKey: 'monitoring.defs.memory_unusual_forgetfulness',
        descriptionTranslationKey: 'monitoring.defs.desc.memory_unusual_forgetfulness',
        fieldType: 'text',
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000023',
        code: 'memory_repeated_questions',
        name: 'Repetição de perguntas',
        description: 'Percebido questionamentos repetidos sobre o mesmo tema.',
        translationKey: 'monitoring.defs.memory_repeated_questions',
        descriptionTranslationKey: 'monitoring.defs.desc.memory_repeated_questions',
        fieldType: 'boolean',
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000024',
        code: 'memory_routine_difficulty',
        name: 'Dificuldade em seguir a rotina',
        description: 'Necessidade de auxílio em passos cotidianos conhecidos.',
        translationKey: 'monitoring.defs.memory_routine_difficulty',
        descriptionTranslationKey: 'monitoring.defs.desc.memory_routine_difficulty',
        fieldType: 'text',
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000025',
        code: 'memory_reminder_need',
        name: 'Necessidade de lembretes adicionais',
        description: 'Avisos extras para compromissos do dia.',
        translationKey: 'monitoring.defs.memory_reminder_need',
        descriptionTranslationKey: 'monitoring.defs.desc.memory_reminder_need',
        fieldType: 'boolean',
        displayOrder: 4,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000005',
    code: 'autonomy',
    name: 'Autonomia nas tarefas',
    translationKey: 'monitoring.categories.autonomy',
    icon: 'Footprints',
    displayOrder: 5,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000026',
        code: 'autonomy_meals',
        name: 'Alimentou-se sozinho ou com ajuda',
        description: 'Nível de auxílio necessário durante a alimentação.',
        translationKey: 'monitoring.defs.autonomy_meals',
        descriptionTranslationKey: 'monitoring.defs.desc.autonomy_meals',
        fieldType: 'select',
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000027',
        code: 'autonomy_bath',
        name: 'Banho sozinho ou assistido',
        description: 'Se o banho ocorreu de forma independente ou acompanhada.',
        translationKey: 'monitoring.defs.autonomy_bath',
        descriptionTranslationKey: 'monitoring.defs.desc.autonomy_bath',
        fieldType: 'select',
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000028',
        code: 'autonomy_dressing',
        name: 'Vestir-se sozinho ou com apoio',
        description: 'Autonomia para escolher e vestir roupas.',
        translationKey: 'monitoring.defs.autonomy_dressing',
        descriptionTranslationKey: 'monitoring.defs.desc.autonomy_dressing',
        fieldType: 'select',
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000029',
        code: 'autonomy_mobility',
        name: 'Locomoção (sozinho, bengala, andador, cadeira)',
        description: 'Uso de auxílio para caminhar no dia a dia.',
        translationKey: 'monitoring.defs.autonomy_mobility',
        descriptionTranslationKey: 'monitoring.defs.desc.autonomy_mobility',
        fieldType: 'select',
        displayOrder: 4,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000030',
        code: 'autonomy_restroom',
        name: 'Uso do banheiro sozinho ou assistido',
        description: 'Necessidade de suporte ao ir ao banheiro.',
        translationKey: 'monitoring.defs.autonomy_restroom',
        descriptionTranslationKey: 'monitoring.defs.desc.autonomy_restroom',
        fieldType: 'select',
        displayOrder: 5,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000006',
    code: 'socialization',
    name: 'Socialização e conexões',
    translationKey: 'monitoring.categories.socialization',
    icon: 'Users',
    displayOrder: 6,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000031',
        code: 'social_visits',
        name: 'Visitas recebidas',
        description: 'Familiares, amigos ou profissionais que visitaram.',
        translationKey: 'monitoring.defs.social_visits',
        descriptionTranslationKey: 'monitoring.defs.desc.social_visits',
        fieldType: 'text',
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000032',
        code: 'social_calls',
        name: 'Ligações e videochamadas',
        description: 'Contatos telefônicos ou chamadas de vídeo com familiares.',
        translationKey: 'monitoring.defs.social_calls',
        descriptionTranslationKey: 'monitoring.defs.desc.social_calls',
        fieldType: 'number',
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000033',
        code: 'social_activities',
        name: 'Atividades em grupo ou saídas',
        description: 'Passeios, eventos familiares e saídas de casa.',
        translationKey: 'monitoring.defs.social_activities',
        descriptionTranslationKey: 'monitoring.defs.desc.social_activities',
        fieldType: 'text',
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000034',
        code: 'social_alone_periods',
        name: 'Períodos prolongados sozinho',
        description: 'Registro de momentos sem companhia para acompanhamento.',
        translationKey: 'monitoring.defs.social_alone_periods',
        descriptionTranslationKey: 'monitoring.defs.desc.social_alone_periods',
        fieldType: 'boolean',
        displayOrder: 4,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000007',
    code: 'safety_incidents',
    name: 'Segurança e ocorrências',
    translationKey: 'monitoring.categories.safety_incidents',
    icon: 'ShieldAlert',
    displayOrder: 7,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000035',
        code: 'safety_falls',
        name: 'Quedas e quase quedas',
        description: 'Data, horário, local, testemunhas e ação tomada.',
        translationKey: 'monitoring.defs.safety_falls',
        descriptionTranslationKey: 'monitoring.defs.desc.safety_falls',
        fieldType: 'text',
        allowsAttachment: true,
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000036',
        code: 'safety_domestic_incidents',
        name: 'Incidentes domésticos',
        description: 'Pequenos acidentes ou ocorrências no ambiente do lar.',
        translationKey: 'monitoring.defs.safety_domestic_incidents',
        descriptionTranslationKey: 'monitoring.defs.desc.safety_domestic_incidents',
        fieldType: 'text',
        allowsAttachment: true,
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000037',
        code: 'safety_help_requests',
        name: 'Pedidos de ajuda',
        description: 'Acionamentos do botão de socorro ou chamada da família.',
        translationKey: 'monitoring.defs.safety_help_requests',
        descriptionTranslationKey: 'monitoring.defs.desc.safety_help_requests',
        fieldType: 'boolean',
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000038',
        code: 'safety_emergency_button',
        name: 'Botão de emergência',
        description: 'Habilita o botão fixo de emergência com contatos autorizados.',
        translationKey: 'monitoring.defs.safety_emergency_button',
        descriptionTranslationKey: 'monitoring.defs.desc.safety_emergency_button',
        fieldType: 'boolean',
        displayOrder: 4,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000039',
        code: 'safety_observed_wounds',
        name: 'Feridas ou lesões observadas',
        description: 'Registro visual com autorização da família.',
        translationKey: 'monitoring.defs.safety_observed_wounds',
        descriptionTranslationKey: 'monitoring.defs.desc.safety_observed_wounds',
        fieldType: 'text',
        allowsAttachment: true,
        displayOrder: 5,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000008',
    code: 'prosthetics_devices',
    name: 'Próteses, equipamentos e dispositivos',
    translationKey: 'monitoring.categories.prosthetics_devices',
    icon: 'Glasses',
    displayOrder: 8,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000040',
        code: 'devices_glasses',
        name: 'Óculos de grau',
        description: 'Uso, limpeza e localização dos óculos.',
        translationKey: 'monitoring.defs.devices_glasses',
        descriptionTranslationKey: 'monitoring.defs.desc.devices_glasses',
        fieldType: 'boolean',
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000041',
        code: 'devices_hearing_aid',
        name: 'Aparelho auditivo',
        description: 'Uso, troca de baterias e higienização.',
        translationKey: 'monitoring.defs.devices_hearing_aid',
        descriptionTranslationKey: 'monitoring.defs.desc.devices_hearing_aid',
        fieldType: 'boolean',
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000042',
        code: 'devices_dentures',
        name: 'Prótese dentária',
        description: 'Uso, higienização e conforto bucal.',
        translationKey: 'monitoring.defs.devices_dentures',
        descriptionTranslationKey: 'monitoring.defs.desc.devices_dentures',
        fieldType: 'boolean',
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000043',
        code: 'devices_mobility_aids',
        name: 'Dispositivos de apoio (bengala / andador / cadeira)',
        description: 'Conservação e manutenção periódica.',
        translationKey: 'monitoring.defs.devices_mobility_aids',
        descriptionTranslationKey: 'monitoring.defs.desc.devices_mobility_aids',
        fieldType: 'select',
        displayOrder: 4,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000009',
    code: 'care_inventory',
    name: 'Estoque de cuidados',
    translationKey: 'monitoring.categories.care_inventory',
    icon: 'Package',
    displayOrder: 9,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000044',
        code: 'inventory_diapers',
        name: 'Estoque de fraldas descartáveis',
        description: 'Quantidade de pacotes e alerta de reposição.',
        translationKey: 'monitoring.defs.inventory_diapers',
        descriptionTranslationKey: 'monitoring.defs.desc.inventory_diapers',
        fieldType: 'number',
        allowsReminder: true,
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000045',
        code: 'inventory_hygiene',
        name: 'Itens de higiene e banho',
        description: 'Sabonetes especiais, hidratantes e produtos pessoais.',
        translationKey: 'monitoring.defs.inventory_hygiene',
        descriptionTranslationKey: 'monitoring.defs.desc.inventory_hygiene',
        fieldType: 'number',
        allowsReminder: true,
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000046',
        code: 'inventory_dressings',
        name: 'Materiais de curativo',
        description: 'Gazes, fitas e produtos informados pela família.',
        translationKey: 'monitoring.defs.inventory_dressings',
        descriptionTranslationKey: 'monitoring.defs.desc.inventory_dressings',
        fieldType: 'number',
        allowsReminder: true,
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000047',
        code: 'inventory_special_food',
        name: 'Alimentação especial e suplementos orientados',
        description: 'Controle de caixas e latas cadastradas pela família.',
        translationKey: 'monitoring.defs.inventory_special_food',
        descriptionTranslationKey: 'monitoring.defs.desc.inventory_special_food',
        fieldType: 'number',
        allowsReminder: true,
        displayOrder: 4,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000010',
    code: 'schedule_logistics',
    name: 'Agenda, transporte e documentos',
    translationKey: 'monitoring.categories.schedule_logistics',
    icon: 'Calendar',
    displayOrder: 10,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000048',
        code: 'schedule_appointments',
        name: 'Consultas e exames',
        description: 'Agendamentos médicos, preparos e especialistas.',
        translationKey: 'monitoring.defs.schedule_appointments',
        descriptionTranslationKey: 'monitoring.defs.desc.schedule_appointments',
        fieldType: 'text',
        allowsReminder: true,
        allowsAttachment: true,
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000049',
        code: 'schedule_physical_therapy',
        name: 'Fisioterapia e terapias',
        description: 'Sessões semanais e orientações de profissionais.',
        translationKey: 'monitoring.defs.schedule_physical_therapy',
        descriptionTranslationKey: 'monitoring.defs.desc.schedule_physical_therapy',
        fieldType: 'text',
        allowsReminder: true,
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000050',
        code: 'schedule_transport',
        name: 'Transporte e acompanhante',
        description: 'Motorista responsável, carro e trajeto.',
        translationKey: 'monitoring.defs.schedule_transport',
        descriptionTranslationKey: 'monitoring.defs.desc.schedule_transport',
        fieldType: 'text',
        displayOrder: 3,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000051',
        code: 'schedule_documents',
        name: 'Documentos, receitas e carteirinha',
        description: 'Validade de guias, pedidos médicos e convênios.',
        translationKey: 'monitoring.defs.schedule_documents',
        descriptionTranslationKey: 'monitoring.defs.desc.schedule_documents',
        fieldType: 'text',
        allowsAttachment: true,
        displayOrder: 4,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000011',
    code: 'caregivers_shifts',
    name: 'Cuidadores e passagem de turno',
    translationKey: 'monitoring.categories.caregivers_shifts',
    icon: 'Clock',
    displayOrder: 11,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000052',
        code: 'shift_checkin_checkout',
        name: 'Início e fim de turno do cuidador',
        description: 'Check-in com horário do profissional responsável.',
        translationKey: 'monitoring.defs.shift_checkin_checkout',
        descriptionTranslationKey: 'monitoring.defs.desc.shift_checkin_checkout',
        fieldType: 'time',
        displayOrder: 1,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000053',
        code: 'shift_tasks',
        name: 'Tarefas e checklist do plantão',
        description: 'Atividades pendentes e concluídas no horário.',
        translationKey: 'monitoring.defs.shift_tasks',
        descriptionTranslationKey: 'monitoring.defs.desc.shift_tasks',
        fieldType: 'text',
        displayOrder: 2,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000054',
        code: 'shift_handover_report',
        name: 'Relatório e passagem de turno',
        description: 'Resumo com confirmação de leitura do próximo cuidador.',
        translationKey: 'monitoring.defs.shift_handover_report',
        descriptionTranslationKey: 'monitoring.defs.desc.shift_handover_report',
        fieldType: 'text',
        displayOrder: 3,
      },
    ],
  },
  {
    id: 'c1000000-0000-0000-0000-000000000012',
    code: 'cared_person_checkins',
    name: 'Botões da tela simplificada (Pessoa Cuidada)',
    translationKey: 'monitoring.categories.cared_person_checkins',
    icon: 'CheckSquare',
    displayOrder: 12,
    definitions: [
      {
        id: 'd1000000-0000-0000-0000-000000000055',
        code: 'checkin_btn_im_well',
        name: 'Botão "Estou bem"',
        description: 'Avisa a família com 1 toque que tudo está tranquilo.',
        translationKey: 'monitoring.defs.checkin_btn_im_well',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_im_well',
        fieldType: 'boolean',
        displayOrder: 1,
        isCheckinButton: true,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000056',
        code: 'checkin_btn_need_help',
        name: 'Botão "Preciso de ajuda"',
        description: 'Emite um alerta sonoro e notificação para a família.',
        translationKey: 'monitoring.defs.checkin_btn_need_help',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_need_help',
        fieldType: 'boolean',
        displayOrder: 2,
        isCheckinButton: true,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000057',
        code: 'checkin_btn_took_med',
        name: 'Botão "Tomei o remédio"',
        description: 'Registra a confirmação do horário de medicação com botão gigante.',
        translationKey: 'monitoring.defs.checkin_btn_took_med',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_took_med',
        fieldType: 'boolean',
        dependencyCode: 'meds_scheduled',
        displayOrder: 3,
        isCheckinButton: true,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000058',
        code: 'checkin_btn_ate',
        name: 'Botão "Já me alimentei"',
        description: 'Confirmação rápida da refeição atual.',
        translationKey: 'monitoring.defs.checkin_btn_ate',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_ate',
        fieldType: 'boolean',
        dependencyCode: 'routine_meals',
        displayOrder: 4,
        isCheckinButton: true,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000059',
        code: 'checkin_btn_drank_water',
        name: 'Botão "Bebi água"',
        description: 'Soma um copo na meta de hidratação do dia.',
        translationKey: 'monitoring.defs.checkin_btn_drank_water',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_drank_water',
        fieldType: 'boolean',
        dependencyCode: 'routine_hydration',
        displayOrder: 5,
        isCheckinButton: true,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000060',
        code: 'checkin_btn_woke_up',
        name: 'Botão "Acordei"',
        description: 'Registra o despertar e informa a família que o dia começou.',
        translationKey: 'monitoring.defs.checkin_btn_woke_up',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_woke_up',
        fieldType: 'boolean',
        dependencyCode: 'routine_sleep',
        displayOrder: 6,
        isCheckinButton: true,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000061',
        code: 'checkin_btn_going_to_sleep',
        name: 'Botão "Vou dormir"',
        description: 'Registra o início do descanso noturno.',
        translationKey: 'monitoring.defs.checkin_btn_going_to_sleep',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_going_to_sleep',
        fieldType: 'boolean',
        dependencyCode: 'routine_sleep',
        displayOrder: 7,
        isCheckinButton: true,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000062',
        code: 'checkin_btn_activity_done',
        name: 'Botão "Concluí minha atividade"',
        description: 'Comunica o término de caminhada, leitura ou fisioterapia.',
        translationKey: 'monitoring.defs.checkin_btn_activity_done',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_activity_done',
        fieldType: 'boolean',
        dependencyCode: 'routine_activities',
        displayOrder: 8,
        isCheckinButton: true,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000063',
        code: 'checkin_btn_remind_later',
        name: 'Botão "Lembrar mais tarde"',
        description: 'Adia um aviso por 15 minutos de forma amigável.',
        translationKey: 'monitoring.defs.checkin_btn_remind_later',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_remind_later',
        fieldType: 'boolean',
        displayOrder: 9,
        isCheckinButton: true,
      },
      {
        id: 'd1000000-0000-0000-0000-000000000064',
        code: 'checkin_btn_emergency',
        name: 'Botão "Emergência"',
        description: 'Botão de destaque vermelho para alertas críticos imediatos.',
        translationKey: 'monitoring.defs.checkin_btn_emergency',
        descriptionTranslationKey: 'monitoring.defs.desc.checkin_btn_emergency',
        fieldType: 'boolean',
        dependencyCode: 'safety_emergency_button',
        displayOrder: 10,
        isCheckinButton: true,
      },
    ],
  },
];

export function getDefinitionByCode(code: string): CatalogDefinition | null {
  for (const cat of MONITORING_CATALOG) {
    const found = cat.definitions.find((d) => d.code === code);
    if (found) return found;
  }
  return null;
}

export function validateDependencies(enabledCodes: string[]): { valid: boolean; missingDependencies: { itemCode: string; requiredCode: string }[] } {
  const missing: { itemCode: string; requiredCode: string }[] = [];
  const enabledSet = new Set(enabledCodes);

  for (const code of enabledCodes) {
    const def = getDefinitionByCode(code);
    if (def?.dependencyCode && !enabledSet.has(def.dependencyCode)) {
      missing.push({ itemCode: code, requiredCode: def.dependencyCode });
    }
  }

  return {
    valid: missing.length === 0,
    missingDependencies: missing,
  };
}
